# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180206_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='payload',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='log',
            name='result',
            field=models.TextField(max_length=10000),
        ),
    ]
