# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170905_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('creator', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10000)),
                ('deviceinfo', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Advertisement')),
            ],
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
